name: Terraform - Azure Container Apps and WAF provision to Demo env

trigger: none

variables:
  - group: Terraform-SPn
  - name: rootFolder
    value: '/'
  - name: tfvarsFile
    value: 'tf.demo.tfvars'
  - name: adoEnvironment
    value: 'demo'
  
stages:
- template: templates/tf-demo-template.yml
  parameters:
    rootFolder: $(rootFolder)
    adoEnvironment: $(adoEnvironment)